name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install libspatialindex
      run: |
        sudo apt-get update
        sudo apt-get install curl
        sudo apt-get install g++
        sudo apt-get install make
        curl -L http://download.osgeo.org/libspatialindex/spatialindex-src-1.8.5.tar.gz | tar xz
        cd spatialindex-src-1.8.5
        ./configure
        sudo make
        sudo make install
        sudo ldconfig
    - name: Install and configure Poetry
      uses: snok/install-poetry@v1.3.3
      with:
        version: 1.7.1
        virtualenvs-create: false
    - name: Install dependencies
      run: |
        poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi
    - name: Lint with black
      run: |
        poetry run black --check .
    - name: Test with pytest
      run: |
        python -m pytest --verbose --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

